language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - cp deploy/machines_user_example.yml deploy/machines_user.yml
  - ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - echo "Host localhost" >> /home/travis/.ssh/config
  - echo "  StrictHostKeyChecking no" >> /home/travis/.ssh/config
  - chmod g-rw,o-rw /home/travis/.ssh/*
script:
  - python -m pytest tests/ 
