language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - sed "s/james/`whoami`/g" <<< cat deploy/machines_user_example.yml > deploy/machines_user.yml
  - rm ~/.ssh/id_rsa
  - ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - chmod og-wx ~/.ssh/authorized_keys
  - ssh-keyscan -H localhost >> ~/.ssh/known_hosts
  - fab localhost install_plugin:FabDummy
  - fab localhost dummy:dummy_test
script:
  - python -m pytest tests/ 
