matrix:
  include:
    - stage: testing
      language: python
      python:
        - "3.6"
      install:
        - pip install -r requirements.txt
        - sed "s/your-username/`whoami`/g" <<< cat deploy/machines_user_example.yml > deploy/machines_user.yml
        - rm -f ~/.ssh/id_rsa
        - ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
        - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
        - chmod og-wx ~/.ssh/authorized_keys
        - ssh-keyscan -H localhost >> ~/.ssh/known_hosts
        - fab localhost install_plugin:FabDummy
      script:
        - python -m pytest tests/
        - py.test --pep8 base/

    - stage: building docker image
      sudo: required
      services:
      - docker
      env:
        - secure: "sAYNC0OOIlsyEH/pV/A8mo1tFhnvNnQHstN/2VggIYK7/C5ngxPSfPmjY9MBbXa2nEBR1L9J6O0EsW0iqZHXHmGu8QFa28bRmL2mtVx98zcqQsSU/nmQ32Bl15BlY5f9CPvBvH/OZ5I3whqksDc9IWJVaM3jPPOc0idMVXUrb3cvKlclHMzfTT65pcYKFHgD7rtCbilp8/fnahVBcUVOnmu9S3ODcj3CvQeTsQAtR9B0oiFjM7P6ipylt8F9x1Pi4Ms3qDRIGCe0bdUzT96amwYtVrAKyrSW7nAXzHOdCsnMSiwyoyvAryPPNBQG0j8zU7bW81Qv895hIbt/xLH/Aij9FenOCvI81zPjx5BBCFmG5tGMj3R9f7JjITkQpvu1wnPjIyWdNv4iqTUUmYUgIx9kIUdeCZLcyXThuJBR1TbTO4UTPvYjzCP5peN5504OvygzLxSt8qsYAjp2bThlhp1KYoyM/wh+S7h7UlYfCS/R1xHRyAJiAerMD3FhclYRaX74+EPiXEXZcqKugWT4zoqYjw+R560I/B0m7aHWhj8srH+7uC5NoUS83taDkWjnVHWFW+fkyhHaScjx7SecW0UFeypSVTmuXmWipSp8OXVh4D2o+zmUJ30IICbhAh6jvGXvSQvR5AcAxy+r7CjDBGzSLj6gsJ2RWUpQhQbWse4="
        - secure: "F5h/mZpGiRMpSq7qVll6CLioZZldYuOliia6u9yJfv2TqgjcHyLGbsM1/BDIqdyhy39tPVmjdTwCKCxaqYom9jomqUk5Ecyln4T7dzS7/Sv4JfIahEoymxa6q1oetdrkBCersIAl7TKkr9+SFMudiUs7aRozmXgfR1P1XMP4zUcF587Kt7SM2bQjGDwT6aIB+7M+VjNUYq1ZqCtoOvaKlcjh8s065vArDf3sQz+wyeLQydGgWgGX1xp1TH/18hUMadIkwEyhfT9+rsOzhadhtFFJm8mIsKjWqKE2abI1gBv+7NJbxpjKNF9zCT62tSh6jAOoP66nNQ66P80U9k7GlDK6e3msPwC4mVf4PtTJlZjKQXaPpUu9cLsfQpS5MizOtZPhh9hgdZLmZV8Fwv+eQebfJK7w+KIT0KtEjTmUHhMAUwkZp0yrb99RaiwcodkQmYz7xY6v6gv4j/SRZqZbSKVpenQXT+B1TdweFZ2ide/MZhcG7kdLj7ox9dSItz0HlC7mKN33nYk2/s58iWwAEHXSNlS6Npo/VCf6vVuKqunYMqQRBtl7ilM5Wu77qEvoVukS1yf4xx3znuPZcOT7PE5n+/ngJ3JnlK2czZQZrlC3q02AORfg8jFZ1gJaKMa2ouEdXfWa5y+VZjsABwvK/fEjUVbKFlNKxl/0yX1Js1U="

      before_script:
      - docker pull vecmafabsim3/fabsimdocker || true
      script:
      - docker build --pull --cache-from vecmafabsim3/fabsimdocker --tag vecmafabsim3/fabsimdocker .
      #- docker build --pull --tag vecmafabsim3/fabsimdocker .
      - docker run vecmafabsim3/fabsimdocker
      after_script:
      - docker images
      before_deploy:
      - docker login -u $DOCKER_USER -p $DOCKER_PASS
      deploy:
        provider: script
        script: docker push vecmafabsim3/fabsimdocker
        on:
          branch: master
