matrix:
  include:
    - stage: testing
      language: python
      python:
        - "3.6"
      install:
        - pip install -r requirements.txt
        - sed "s/your-username/`whoami`/g" <<< cat deploy/machines_user_example.yml > deploy/machines_user.yml
        - rm -f ~/.ssh/id_rsa
        - ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
        - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
        - chmod og-wx ~/.ssh/authorized_keys
        - ssh-keyscan -H localhost >> ~/.ssh/known_hosts
        - fab localhost install_plugin:FabDummy
      script:
        - python -m pytest tests/
        - py.test --pep8 base/

    - stage: building docker image
      sudo: required
      services:
      - docker
      env:
        - secure: "Y8c5Lr8hcaxE3WX5jmRO5HCAH5AVxLek6Z8RNZIT1xWSnqECtwG4opP071uWwbJM2dh3077v6vVCHnJxiuTqa3ltt3m3dWfys3dEKdKNivnNLx4EKXFuGWKeAf2tC9OdJAM8zz7XQuDlJ+TufbTvBrMeRKq+HrJawf1skOb2FcDE7ZCsL2xj74fbPH2PSH+oQhFUGm9ztxt++XuAMu+HjacbbUqzq0TFO8bxe4y4L0KKrYIda3VsXtw00/wgEP5SbP99mimc/0nLFoVPxnMkZ4q9TW7wgVZAHD5dZRrIsvgyboxL5ofqNkInQ9BVW+baudGZEfI4rT2AfkIM3JR6yP9ZlI+ImpRpAxacDA/eUocL2laY/RbrgLLPyeIosunfvjfYobISfmksbGvZ7hdqFqTlz450Ga755ParzAyiEF2SbQHsUz2ihadrP2vPz+eCsfQQT0RgYSjirnu1LqajpFNlmxjQqeY7vdK+zTVynNZcJ0jeDfUg6qWoaGUzhFAOOAIctFkxnCFDmEZMr2uiPfXw9sFdQnaiMGT0Vj6P7bT9Q6EUTppPaK+ohKb3vUzQuATnDG8sty8lkjTcBgoZtXe5tZAvBD9LD4adROt/sTzWca2VmgW+ZfhHpQ6Pv/T92aMFMKGNmjAWzRkrR54+0Rh2Y3UuXLS6wjZR5Klbrt4="
        - secure: "ZY0wsQ3gTUuCk2zrS8bTPrH0da878vi8eg6wkJl2zBnYjj7q68GbuWZ5VSRi5RebCBP35SOfqB/+mxhXaLDq1CMyEcVRBh7mb3YjkODf0N5OoxDyas+oKJeQoJNR0Ji4AhlnZMIyNa0YZ/gs2Ui4EO2vzHaoHBvN2Lu/d+cVTTSpLSB7UmTpb+bgZ29PQmz9atB6oabSu6dtESItp/6NRdMlqGDSawdtEGS//+C2cH2gkdPy2pnDRfJcZ1c6TQTJHELYO7TgJlOnPZT80fQT1lEj9YtqroFDiwvMEw3uReDXkUQ3/YVmMIwJGSwmVhOPdYsTyLkpxX4g5FLcpYgATPMtwgymG7MxyyE9znpqZ5smbxb+99rVHYwgZ90EqT/uYORC6kspafXoFKEGOmfXGGmz5iPxwygOcj/S2eB1CR9Qb68PyeXeSzoaUtbgH9Id6jE81MngN0uXYCM6gKbP2TYo39ykq9jlcxZeFhwfJoLsA2TsKZ2JSzkh480kBjrY/RTbVNY22KygmFUGX/d50OhJMt1nx7rVa++6f7bhp+blewV3u2dY2ggOLzsDR0LYmg8rdZ61RAHZbfLiQldNmfPMUEHUEI7c/eFYY8HYpSfNIOwDCbe8twfrQ6quUOZAab/a/5TzkAoO8Tx675GbYG+QN1WcRhslSQtpVy8shgY="


      before_script:
      - docker pull vecmafabsim3/fabsimdocker || true
      script:
      - docker build --pull --cache-from vecmafabsim3/fabsimdocker --tag vecmafabsim3/fabsimdocker .
      #- docker build --pull --tag vecmafabsim3/fabsimdocker .
      - docker run vecmafabsim3/fabsimdocker
      after_script:
      - docker images
      before_deploy:
      - docker login -u $DOCKER_USER -p $DOCKER_PASS
      deploy:
        provider: script
        script: docker push vecmafabsim3/fabsimdocker
        on:
          branch: master
