# Copy this file as machines_user.yml, and fill in your details.
# Details given in the default dictionary will override default settings in machines.yml
# Details given in per-machine dictionaries will override machine settings in machines.yml

default:
  local_results: "~/Codes/FabSim/results"
  local_configs: "~/Codes/FabSim/config_files"
  username: "your-username"
  # home_path_template: "/home/$username"
  # home_path_template: "/Users/$username"  # for OSX users
  # Allows to switch between SSH (default) and GSISSH login.
  manual_gsissh: false
  port: 22
archer:
  username: "user"
  project: "e123"
  budget: "e123-user"
  lammps_exec: "/home/e123/e123/user/lmp_xc30"
localhost:
  lammps_exec: "/home/your-username/bin/lmp_serial"
# SuperMUC phase2 connecting using GSISSH
supermuc2:
  username: "ab12cde"
  project: "fg34hi"
  namd_exec: "/lrz/sys/applications/namd/2.10/mpi.ibmP2/namd2"
  # Password set in the redisexec directory.
  redispwd: "multiple"
  # Switches to GSISSH login from SSH.
  manual_gsissh: true
  port: 2222
bluejoule:
  username: "abc12-def01"
  groupname: "abc01"
  project: "ABC012" #"HCP056"
  namd_exec: "/gpfs/packages/ibm/namd/2.9/bin/namd2"
  ensemble_dir: "rep0/replicas"   

qcg:
  username: "plg<your-username>"
  # flee_location : "/home/plgrid/plgarabnejad/flee" # location of installed flee on the plgrid machine

eagle:
  username: "plg<your-username>"
